# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Criterion
        run: |
          wget cdn.aurelien-boch.fr/utils/install_criterion.sh
          sudo chmod +x install_criterion.sh
          sudo ./install_criterion.sh
      # Runs a set of commands using the runners shell
      - name: Install nasm compiler
        run: |
          sudo apt update
          sudo apt install nasm
      - name: Test if the lib compiles
        run: |
          make
          make re
      - name: Run Unit tests
        run: make tests_run
